print("      |\\       ");
print("_,,,");
print("---");
println(",,_");
print("ZZZzz");
print("/,`.");
print("-'`'");
print("");
print("     -.");
print("  ;-;");
println(";,_");
print("    |,4-  ");
print(") )-,_.");
print(" ,\\ (  ");
println("`'-'");
print("   '-");
print("--''(");
print("_/-");
print("-'  ");
println("`-'\\_)");
